port: 8003

kratos:
  url_browser: "http://kratos:4433"
  url_admin: "http://kratos:4434"
  login_url_browser: "http://localhost:4455"

grpc:
  host: "datasource:50051"

keto:
  read: "http://keto:4466"
  write: "http://keto:4467"