services:
  admin-client:
    build:
      context: ../apps/admin/client
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    restart: unless-stopped
    depends_on:
      admin:
        condition: service_started
    networks:
      - intranet

  admin:
    build:
      context: ../
      dockerfile: apps/admin/Dockerfile
    ports:
      - "8003:8003"
    volumes:
      - type: bind
        source: ../apps/admin/config/config.yml
        target: /root/config.yml
    command: ["./admin", "serve", "--config=/root/config.yml"]
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      datasource:
        condition: service_started
    networks:
      - intranet
      - datasource-net
