services:
  warehouse-client:
    build:
      context: ../apps/warehouse/client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    restart: unless-stopped
    depends_on:
      warehouse:
        condition: service_started
    networks:
      - intranet

  warehouse:
    build:
      context: ../
      dockerfile: apps/warehouse/Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - type: bind
        source: ../apps/warehouse/config/config.yml
        target: /root/config.yml
    command: ["./warehouse", "serve", "--config=/root/config.yml"]
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      datasource:
        condition: service_started
    networks:
      - intranet
      - datasource-net
