server:
    port: 50051

database:
    host: localhost
    port: 5432
    user: warehouse_user
    password: strong_password
    dbname: postgres
    sslmode: disable

creds:
    server_pem: "certs/server.pem"
    server_key_pem: "certs/server_key.pem"
